## Importing Libraries

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Preprocessing

### Training Image Preprocessing

In [4]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [6]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[146.   144.   149.  ]
   [148.5  146.5  151.5 ]
   [147.5  145.5  150.5 ]
   ...
   [139.5  142.5  151.5 ]
   [129.75 132.75 141.75]
   [136.75 139.75 148.75]]

  [[147.   145.   150.  ]
   [148.25 146.25 151.25]
   [147.5  145.5  150.5 ]
   ...
   [133.5  136.5  145.5 ]
   [136.75 139.75 148.75]
   [127.25 130.25 139.25]]

  [[152.25 150.25 155.25]
   [152.   150.   155.  ]
   [146.75 144.75 149.75]
   ...
   [136.   139.   148.  ]
   [137.75 140.75 149.75]
   [126.75 129.75 138.75]]

  ...

  [[ 22.5   23.75  25.  ]
   [ 32.    34.    31.  ]
   [ 62.    67.25  59.75]
   ...
   [ 38.5   54.75  27.5 ]
   [ 82.25 100.25  60.  ]
   [116.   135.75  86.5 ]]

  [[ 27.5   28.5   32.  ]
   [ 27.75  29.5   28.75]
   [ 40.5   45.5   39.5 ]
   ...
   [ 55.    71.    43.5 ]
   [ 74.5   93.    51.5 ]
   [119.5  139.5   88.  ]]

  [[ 30.75  31.75  36.25]
   [ 34.    35.5   36.5 ]
   [ 62.    67.    61.5 ]
   ...
   [ 48.5   64.    38.5 ]
   [ 79.75  98.25  56.75]
   [106.5  126.5   7

## Building Model

In [24]:
from tensorflow.keras.layers import Dense,Conv2D, MaxPool2D, Flatten
from tensorflow.keras.models import Sequential

In [14]:
model = Sequential()

### Building Convolution Layer

In [18]:
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [20]:
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [21]:
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [22]:
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu', input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding= 'same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [25]:
model.add(Flatten())

In [26]:
model.add(Dense(units=1024, activation='relu'))

In [27]:
#Output Layer
model.add(Dense(units=38, activation='softmax'))

### Compiling Model

In [32]:
model.compile(optimizer='adam',loss='categorical_cossentropy',metrics=['accuracy'])

In [33]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 64, 64, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 64, 64, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 32, 32, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 32, 32, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 32, 32, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 16, 16, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 16, 16, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 16, 16, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 8, 8, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 8, 8, 32)            │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 8, 8, 32)            │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 4, 4, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1024)                │         525,312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          38,950 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 648,390 (2.47 MB)

 Trainable params: 648,390 (2.47 MB)

 Non-trainable params: 0 (0.00 B)